# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PHA Backend

on:
  push:
    branches:
      - 'workflow'
  pull_request:
    branches:
      - 'workflow'

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: pha-express-app
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  build:
    name: Build Express App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build:prod
      
    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: dist
        path: dist

    - name: Create env file
      run: |
        echo $ENV_FILE | base64 --decode > .env
        cat .env

    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: env
        path: .env

  deploy-gcr:
    name: Deploy to GCR
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@main
      with:
        name: dist
        path: dist
      
    - name: Download Artifact
      uses: actions/download-artifact@main
      with:
        name: env
        path: .env

    - name: Setup GCloud Auth
      id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCR_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1

    - name: Create env file
      run: |
        ls -la ./
        cat .env

    # Build and push image to Google Container Registry
    - name: Build & Push
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      working-directory: ./

    # Deploy image to Cloud Run
    - name: Deploy GCR
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --port 9000 \
          --allow-unauthenticated
